version: '3'
services: 
    react:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: .
        ports: 
            - 3000:3000
        volumes: 
            - /app/node_modules
            - .:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true
    tests:
        build: 
            dockerfile: Dockerfile.dev
            context: .
        command: ["npm","run","test"]
        volumes: 
            - /app/node_modules
            - .:/app